"""PipeProbe — Self-contained HTML report with regression diff."""
from __future__ import annotations
from datetime import datetime
from pathlib import Path
from pipeprobe.models import SuiteResult

_HTML = """<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PipeProbe — {suite_name}</title>
<style>
:root{{--pass:#16a34a;--fail:#dc2626;--warn:#ca8a04;--bg:#f9fafb;--card:#fff;--border:#e5e7eb;--text:#111827;--muted:#6b7280}}
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:var(--bg);color:var(--text);padding:2rem;max-width:1100px;margin:auto}}
h1{{font-size:1.4rem;font-weight:600}} .meta{{font-size:.8rem;color:var(--muted);margin:.3rem 0 1.5rem}}
.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:.75rem;margin-bottom:1.5rem}}
.stat{{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:.9rem 1rem}}
.stat-label{{font-size:.7rem;color:var(--muted);text-transform:uppercase;letter-spacing:.05em;margin-bottom:.2rem}}
.stat-value{{font-size:1.6rem;font-weight:600}}
.pass{{color:var(--pass)}} .fail{{color:var(--fail)}} .warn{{color:var(--warn)}}
.compare{{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1rem;margin-bottom:1.5rem}}
.compare h2{{font-size:.9rem;font-weight:600;margin-bottom:.6rem}}
.diff-grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:.5rem;font-size:.82rem}}
.diff-card{{background:#f3f4f6;border-radius:6px;padding:.6rem .8rem}}
.diff-label{{color:var(--muted);font-size:.7rem;margin-bottom:.2rem}}
.diff-val{{font-weight:600}}
.reg-alert{{background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:.9rem 1rem;margin-bottom:1.5rem}}
.reg-alert h2{{color:#991b1b;font-size:.9rem;margin-bottom:.5rem}}
.reg-row{{font-size:.82rem;padding:.3rem 0;border-top:1px solid #fecaca}}
table{{width:100%;border-collapse:collapse;background:var(--card);border:1px solid var(--border);border-radius:8px;overflow:hidden;margin-bottom:1.5rem}}
th{{background:#f3f4f6;padding:.5rem .9rem;text-align:left;font-size:.72rem;font-weight:600;color:var(--muted);text-transform:uppercase;letter-spacing:.04em}}
td{{padding:.65rem .9rem;border-top:1px solid var(--border);font-size:.82rem;vertical-align:top}}
tr:hover td{{background:#fafafa}}
.badge{{display:inline-block;padding:2px 8px;border-radius:9999px;font-size:.72rem;font-weight:500}}
.badge-pass{{background:#dcfce7;color:#15803d}} .badge-fail{{background:#fee2e2;color:#b91c1c}}
.metric-line{{font-size:.75rem;margin-top:.2rem}}
.mpass{{color:var(--pass)}} .mfail{{color:var(--fail)}}
.reason{{font-size:.72rem;color:var(--muted);font-style:italic;max-width:360px}}
details summary{{cursor:pointer;color:#2563eb;font-size:.78rem}}
footer{{font-size:.72rem;color:var(--muted);text-align:center;margin-top:1.5rem}}
</style></head><body>

<h1>⚙ PipeProbe — {suite_name}</h1>
<div class="meta">
  run <strong>{run_id}</strong> · branch {git_branch} · sha {git_sha} · {triggered_by} · {started_at} · {duration:.1f}s
</div>

<div class="grid">
  <div class="stat"><div class="stat-label">Pass rate</div><div class="stat-value {pr_cls}">{pass_rate:.1%}</div></div>
  <div class="stat"><div class="stat-label">Avg score</div><div class="stat-value">{avg_score:.3f}</div></div>
  <div class="stat"><div class="stat-label">Passed</div><div class="stat-value pass">{passed}</div></div>
  <div class="stat"><div class="stat-label">Failed</div><div class="stat-value fail">{failed}</div></div>
  <div class="stat"><div class="stat-label">Regressions</div><div class="stat-value {reg_cls}">{regressions}</div></div>
  <div class="stat"><div class="stat-label">Cases</div><div class="stat-value">{total}</div></div>
</div>

{compare_section}
{regression_section}

<table>
<thead><tr>
  <th>Case</th><th>Domain</th><th>Score</th><th>Δ</th>
  <th>Verdict</th><th>Judge</th><th>Latency</th><th>Metrics</th>
</tr></thead>
<tbody>{rows}</tbody>
</table>

<footer>Generated by <strong>PipeProbe</strong> · {generated_at}</footer>
</body></html>"""

_ROW = """<tr>
  <td><strong>{case_id}</strong>{reg_badge}</td>
  <td><code>{domain}</code></td>
  <td style="font-weight:600;color:{score_color}">{score:.3f}</td>
  <td style="color:{delta_color};font-weight:600">{delta}</td>
  <td><span class="badge badge-{verdict_cls}">{verdict}</span></td>
  <td>{judge}</td>
  <td style="color:var(--muted)">{latency:.0f}ms</td>
  <td><details><summary>{metric_summary}</summary>{metric_rows}</details></td>
</tr>"""

_COMPARE = """<div class="compare">
<h2>📊 Regression comparison vs run {prev_run_id}</h2>
<div class="diff-grid">
  <div class="diff-card"><div class="diff-label">Avg score</div>
    <div class="diff-val">{prev_avg:.3f} → {curr_avg:.3f} <span style="color:{avg_col}">{avg_sign}{avg_delta:.3f}</span></div></div>
  <div class="diff-card"><div class="diff-label">Regressions</div>
    <div class="diff-val" style="color:{reg_col2}">{reg_rows_inline}</div></div>
  <div class="diff-card"><div class="diff-label">Improved</div>
    <div class="diff-val" style="color:#16a34a">{imp_rows_inline}</div></div>
</div></div>"""

_REG_SECTION = """<div class="reg-alert">
<h2>⚠ Regressions detected — CI blocked</h2>
{reg_rows}
</div>"""


def generate_html_report(
    suite: SuiteResult,
    compare: dict | None = None,
    output_path: str | Path | None = None,
) -> str:
    rows = ""
    for r in suite.results:
        sc    = r.overall_score
        color = "#16a34a" if sc >= 0.8 else "#ca8a04" if sc >= 0.6 else "#dc2626"
        delta_str = "—"
        delta_col = "var(--muted)"
        if r.delta != 0.0:
            sign      = "+" if r.delta > 0 else ""
            delta_str = f"{sign}{r.delta:.1%}"
            delta_col = "#dc2626" if r.regression else "#16a34a"
        mrows = "".join(
            f'<div class="metric-line"><span class="{"mpass" if m.passed else "mfail"}">'
            f'{"✓" if m.passed else "✗"} {m.name}: {m.score:.3f}</span>'
            f'<div class="reason">{m.reasoning[:180]}</div></div>'
            for m in r.metrics
        )
        failed_names = [m.name for m in r.failed_metrics]
        rows += _ROW.format(
            case_id=r.case_id,
            reg_badge=' <span style="background:#fee2e2;color:#991b1b;font-size:.68rem;padding:1px 5px;border-radius:3px">▼ regression</span>' if r.regression else "",
            domain=r.domain.value, score=sc, score_color=color,
            delta=delta_str, delta_color=delta_col,
            verdict_cls=r.verdict.value, verdict=r.verdict.value,
            judge=r.judge_provider, latency=r.latency_ms,
            metric_summary="all passed" if not failed_names else f"failed: {', '.join(failed_names)}",
            metric_rows=mrows,
        )

    compare_section = ""
    if compare and compare.get("has_baseline"):
        regs = compare.get("regressed", [])
        imps = compare.get("improved",  [])
        avg_delta = compare.get("avg_delta", 0)
        compare_section = _COMPARE.format(
            prev_run_id=compare.get("prev_run_id","?"),
            prev_avg=compare.get("prev_avg",0), curr_avg=compare.get("curr_avg",0),
            avg_delta=abs(avg_delta),
            avg_sign="+" if avg_delta >= 0 else "-",
            avg_col="#16a34a" if avg_delta >= 0 else "#dc2626",
            reg_col2="#dc2626" if regs else "#16a34a",
            reg_rows_inline=", ".join(f"{r['case_id']} ({r['delta']:+.2f})" for r in regs) or "none",
            imp_rows_inline=", ".join(f"{i['case_id']} ({i['delta']:+.2f})" for i in imps) or "none",
        )

    regression_section = ""
    if suite.regressions:
        reg_rows_html = "".join(
            f'<div class="reg-row">▼ <strong>{r.case_id}</strong> '
            f'({r.domain.value}) — score {r.overall_score:.3f} '
            f'<span style="color:#dc2626">dropped {r.delta:.1%}</span> '
            f'vs prev {r.prev_score:.3f}</div>'
            for r in suite.regressions
        )
        regression_section = _REG_SECTION.format(reg_rows=reg_rows_html)

    pr  = suite.pass_rate
    pr_cls  = "pass" if pr >= 0.8 else "warn" if pr >= 0.6 else "fail"
    reg_cls = "fail" if suite.regressions else "pass"

    html = _HTML.format(
        suite_name=suite.suite_name, run_id=suite.run_id,
        git_branch=suite.git_branch or "local",
        git_sha=suite.git_sha[:8] if suite.git_sha else "n/a",
        triggered_by=suite.triggered_by,
        started_at=suite.started_at.strftime("%Y-%m-%d %H:%M UTC"),
        duration=suite.duration_seconds,
        pass_rate=pr, pr_cls=pr_cls,
        avg_score=suite.avg_score,
        passed=suite.passed, failed=suite.failed,
        regressions=len(suite.regressions), reg_cls=reg_cls,
        total=suite.total,
        compare_section=compare_section,
        regression_section=regression_section,
        rows=rows,
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
    )
    if output_path:
        Path(output_path).write_text(html)
    return html
